# Generated by Django 4.2.1 on 2023-12-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='surname',
        ),
    ]
