# Generated by Django 4.2.1 on 2023-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_alter_courier_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(default='Свободен', max_length=20),
        ),
    ]
