# Generated by Django 4.2.1 on 2023-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_alter_courier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('Свободен', 'FREE'), ('Занят', 'BUSY')], default='Свободен', max_length=20),
        ),
    ]
