# Generated by Django 4.2.7 on 2023-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
        ('client', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ManyToManyField(blank=True, to='pharmacist.pharmacy'),
        ),
    ]
