# Generated by Django 4.2.7 on 2023-12-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
        ('client', '0004_order_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacist.pharmacy'),
        ),
    ]
