# Generated by Django 4.2.7 on 2023-12-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
        ('client', '0005_remove_order_pharmacy_order_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacist.pharmacy'),
        ),
    ]
