# Generated by Django 4.2.7 on 2023-12-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0002_remove_medicine_pharmacies_alter_pharmacy_image_and_more'),
        ('client', '0008_alter_order_status_favourite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'medicine')},
        ),
    ]
