# Generated by Django 4.2.7 on 2023-12-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
