# Generated by Django 4.2.7 on 2023-12-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0003_pharmacy_latitude_pharmacy_longitude'),
        ('client', '0011_alter_client_address_alter_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='temp_pharmacy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacist.pharmacy'),
        ),
    ]
