# Generated by Django 4.2.7 on 2023-12-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название аптеки')),
                ('image', models.ImageField(upload_to='pharmacy_images/')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес аптеки')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона аптеки')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirience', models.PositiveIntegerField()),
                ('license_number', models.PositiveIntegerField()),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacist.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='medicine_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('type_of_med', models.CharField(max_length=255)),
                ('manuf_date', models.DateField(auto_now_add=True)),
                ('usage', models.CharField(max_length=255)),
                ('indications', models.CharField(max_length=255)),
                ('pharmacies', models.ManyToManyField(to='pharmacist.pharmacy')),
            ],
        ),
    ]
