# Generated by Django 4.2.7 on 2023-12-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacies',
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(upload_to='pharmacy/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacist.pharmacy'),
        ),
    ]
